#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧪 Running tests before pushing..."

# Run tests
echo "Running tests..."
# //TODO:  Add test here 
# npm test || { echo "❌ Tests failed"; exit 1; }

echo "✅ All checks passed! Pushing to remote..."